# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tutor', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('result_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lab', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mem_num', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('apply_year', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('apply_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('middle_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('conclude_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('file_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
