# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userproinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproinfo',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
